apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: domagalsky/demo-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
        env:
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: redis-password

      initContainers:
      - name: init-redis-svc-conn-check
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup redis; do echo waiting for redis service; sleep 2; done"]
      - name: init-redis-ping-pong-show
        image: redis:6.2.6
        command:
          - redis-cli
        args:
          - -h
          - redis
          - -a
          - $(REDIS_PASSWORD)
          - ping
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: redis-password
